In [1]:
import pandas as pd
import numpy as np

## Vivienda

In [19]:
file = "../../dataframes/enigh/enigh_clean_2016.csv"

In [20]:
df = pd.read_csv(filepath_or_buffer=file)

In [21]:
df.shape

(70311, 124)

In [22]:
df.isnull().any().any()

False

In [25]:
df.head()

Unnamed: 0  tam_loc  est_socio  clase_hog  sexo_jefe  edad_jefe  \
0           0        1          4          2          1         33   
1           1        1          4          2          1         29   
2           2        1          4          2          1         47   
3           3        1          4          3          2         29   
4           4        1          4          2          1         55   

   educa_jefe  tot_integ  hombres  mujeres ...   deposito  prest_terc  \
0          10          2        1        1 ...        0.0         0.0   
1          10          2        1        1 ...        0.0         0.0   
2          10          6        2        4 ...        0.0         0.0   
3          11          3        0        3 ...        0.0         0.0   
4          10          2        2        0 ...        0.0         0.0   

   pago_tarje  deudas  balance  otras_erog     smg  ent  mun  loc  
0    17409.83     0.0      0.0         0.0  6573.6    1    1    0  
1     5360.65     0.0      0.0         0.0  6573.6    1    1    0  
2    23606.55     0.0      0.0         0.0  6573.6    1    1    0  
3     8852.45     0.0      0.0         0.0  6573.6    1    1    0  
4        0.00     0.0      0.0         0.0  6573.6    1    1    0  

[5 rows x 124 columns]

In [33]:
df_copy = df.copy()

In [34]:
df_copy.drop(labels=['Unnamed: 0', 'smg'], axis=1, inplace=True)

In [35]:
df_copy.columns

Index(['tam_loc', 'est_socio', 'clase_hog', 'sexo_jefe', 'edad_jefe',
       'educa_jefe', 'tot_integ', 'hombres', 'mujeres', 'mayores',
       ...
       'servicio', 'deposito', 'prest_terc', 'pago_tarje', 'deudas', 'balance',
       'otras_erog', 'ent', 'mun', 'loc'],
      dtype='object', length=122)

In [36]:
categoricos = ['tam_loc', 'est_socio', 'clase_hog', 'sexo_jefe', 'educa_jefe']

In [38]:
numericos = []

for row in df_copy.columns:
    if row not in categoricos:
        if (row != 'ent') & (row != 'mun') & (row != 'loc'):
#            print(row)
            numericos.append(row)
            
numericos

['edad_jefe',
 'tot_integ',
 'hombres',
 'mujeres',
 'mayores',
 'menores',
 'p12_64',
 'p65mas',
 'ocupados',
 'percep_ing',
 'perc_ocupa',
 'ing_cor',
 'ingtrab',
 'trabajo',
 'sueldos',
 'horas_extr',
 'comisiones',
 'aguinaldo',
 'indemtrab',
 'otra_rem',
 'remu_espec',
 'negocio',
 'noagrop',
 'industria',
 'comercio',
 'servicios',
 'agrope',
 'agricolas',
 'pecuarios',
 'reproducc',
 'pesca',
 'otros_trab',
 'rentas',
 'utilidad',
 'arrenda',
 'transfer',
 'jubilacion',
 'becas',
 'donativos',
 'remesas',
 'bene_gob',
 'transf_hog',
 'trans_inst',
 'estim_alqu',
 'otros_ing',
 'gasto_mon',
 'alimentos',
 'ali_dentro',
 'cereales',
 'carnes',
 'pescado',
 'leche',
 'huevo',
 'aceites',
 'tuberculo',
 'verduras',
 'frutas',
 'azucar',
 'cafe',
 'especias',
 'otros_alim',
 'bebidas',
 'ali_fuera',
 'tabaco',
 'vesti_calz',
 'vestido',
 'calzado',
 'vivienda',
 'alquiler',
 'pred_cons',
 'agua',
 'energia',
 'limpieza',
 'cuidados',
 'utensilios',
 'enseres',
 'salud',
 'atenc_ambu'

In [39]:
df_copy.shape

(70311, 122)

In [40]:
len(numericos) + len (categoricos) + 3

122

In [41]:
df_transform = pd.DataFrame()
dicc_transform = {}

In [42]:
for element in categoricos:
    i = 0
    column = element
    
    print(element)

    grouped = pd.DataFrame(df_copy[column].dropna().value_counts())
    grouped.head()

    grouped.reset_index(inplace=True)
    grouped.columns

    grouped.rename(columns={0: 'Key'}, inplace=True)
    grouped.columns

    grouped

    list_ = []
    for row in grouped[column]:
    #    print("%.2f" % (row/df_copy.shape[0]))
        list_.append(row/df_copy.shape[0])

    list_

    grouped[column] = list_
    grouped

    dict_ = grouped.to_dict(orient='split')
    dict_.keys()

    dict_.pop('index')
    dict_.pop('columns')
    dict_

    dict__ = {}

    for line in dict_['data']:
        #print(line[1], ' : ', line[0])
        dict__[line[0]] = line[1]
        i = i + 1
    dict__
    print(i)
        
    df_transform[column] = df_copy[column].replace(dict__)
    print(df_copy[column].unique())
    print(df_transform[column].unique())


tam_loc
4
[1 2 3 4]
[0.37282929 0.1281734  0.13441709 0.36458022]
est_socio
4
[4 3 2 1]
[0.06604941 0.17726956 0.52887884 0.22780219]
clase_hog
5
[2 3 1 4 5]
[0.6453471  0.23333476 0.11039524 0.00738149 0.00354141]
sexo_jefe
2
[1 2]
[0.73840509 0.26159491]
educa_jefe
11
[10 11  8  4  3  6  1  7  9  5  2]
[0.08665785 0.01695325 0.10537469 0.17624554 0.17746867 0.26239138
 0.07663097 0.03373583 0.02700858 0.03660878 0.00092446]


In [43]:
df_transform['ent'] = df_copy.ent

In [44]:
df_transform['mun'] = df_copy.mun

In [45]:
df_transform['loc'] = df_copy['loc']

In [46]:
df_transform[numericos] = df_copy[numericos]

In [47]:
df_transform.columns

Index(['tam_loc', 'est_socio', 'clase_hog', 'sexo_jefe', 'educa_jefe', 'ent',
       'mun', 'loc', 'edad_jefe', 'tot_integ',
       ...
       'cuota_viv', 'mater_serv', 'material', 'servicio', 'deposito',
       'prest_terc', 'pago_tarje', 'deudas', 'balance', 'otras_erog'],
      dtype='object', length=122)

In [48]:
df_transform.shape

(70311, 122)

In [51]:
df_transform.drop(labels=['loc'], axis=1, inplace=True)

In [52]:
file = "../../dataframes/enigh/enigh_transf_2016.csv"

In [53]:
df_transform.to_csv(path_or_buf=file)