In [5]:
import pandas as pd
import numpy as np

## Vivienda

In [6]:
file = "../../dataframes/enoe/enoe_clean_2016.csv"

In [7]:
df = pd.read_csv(filepath_or_buffer=file)

In [8]:
df.shape

(313968, 75)

In [9]:
df.isnull().any().any()

False

In [10]:
df.head()

Unnamed: 0  loc  mun  est  t_loc  ent  sex   eda  nac_dia  nac_mes  \
0           0    1    2   10      1    9    2  27.0     25.0      8.0   
1           1    1    2   10      1    9    1  45.0     16.0      2.0   
2           2    1    2   10      1    9    2  48.0     24.0      9.0   
3           3    1    2   10      1    9    2  24.0     18.0     10.0   
4           4    1    2   10      1    9    1  54.0     23.0      6.0   

    ...     ma48me1sm  p14apoyos  scian  t_tra  emp_ppal  tue_ppal  \
0   ...             0          2      7      1         2         2   
1   ...             0          2      5      2         1         1   
2   ...             0          2     18      1         2         2   
3   ...             0          2      0      1         0         0   
4   ...             0          2     19      1         1         1   

   trans_ppal  mh_fil2  mh_col  sec_ins  
0           0        3       2        2  
1           0        1       7        8  
2           0        3       8        4  
3           0        0       0        0  
4           0        1       5        8  

[5 rows x 75 columns]

In [22]:
df_copy = df.copy()

In [23]:
df_copy.drop(labels=['Unnamed: 0'], axis=1, inplace=True)

In [24]:
df_copy.columns

Index(['loc', 'mun', 'est', 't_loc', 'ent', 'sex', 'eda', 'nac_dia', 'nac_mes',
       'nac_anio', 'l_nac_c', 'cs_p12', 'cs_p13_1', 'cs_p13_2', 'cs_p17',
       'e_con', 'clase1', 'clase2', 'clase3', 'pos_ocu', 'seg_soc', 'rama',
       'c_ocu11c', 'ing7c', 'dur9c', 'emple7c', 'medica5c', 'buscar5c',
       'rama_est1', 'rama_est2', 'dur_est', 'ambito1', 'ambito2', 'tue1',
       'tue2', 'tue3', 'busqueda', 'd_ant_lab', 'd_cexp_est', 'dur_des',
       'sub_o', 's_clasifi', 'remune2c', 'pre_asa', 'tip_con', 'dispo',
       'nodispo', 'c_inac5c', 'pnea_est', 'niv_ins', 'eda5c', 'eda7c',
       'eda12c', 'eda19c', 'hij5c', 'domestico', 'anios_esc', 'hrsocup',
       'ingocup', 'ing_x_hrs', 'tpg_p8a', 'tcco', 'cp_anoc', 'imssissste',
       'ma48me1sm', 'p14apoyos', 'scian', 't_tra', 'emp_ppal', 'tue_ppal',
       'trans_ppal', 'mh_fil2', 'mh_col', 'sec_ins'],
      dtype='object')

In [25]:
numericos = ['eda', 'nac_dia', 'nac_mes', 'nac_anio', 'anios_esc', 'hrsocup', 
             'ingocup', 'ing_x_hrs', 't_tra']

In [26]:
categoricos = []

for row in df_copy.columns:
    if row not in numericos:
        if (row != 'ent') & (row != 'mun') & (row != 'loc'):
#            print(row)
            categoricos.append(row)
            
categoricos

['est',
 't_loc',
 'sex',
 'l_nac_c',
 'cs_p12',
 'cs_p13_1',
 'cs_p13_2',
 'cs_p17',
 'e_con',
 'clase1',
 'clase2',
 'clase3',
 'pos_ocu',
 'seg_soc',
 'rama',
 'c_ocu11c',
 'ing7c',
 'dur9c',
 'emple7c',
 'medica5c',
 'buscar5c',
 'rama_est1',
 'rama_est2',
 'dur_est',
 'ambito1',
 'ambito2',
 'tue1',
 'tue2',
 'tue3',
 'busqueda',
 'd_ant_lab',
 'd_cexp_est',
 'dur_des',
 'sub_o',
 's_clasifi',
 'remune2c',
 'pre_asa',
 'tip_con',
 'dispo',
 'nodispo',
 'c_inac5c',
 'pnea_est',
 'niv_ins',
 'eda5c',
 'eda7c',
 'eda12c',
 'eda19c',
 'hij5c',
 'domestico',
 'tpg_p8a',
 'tcco',
 'cp_anoc',
 'imssissste',
 'ma48me1sm',
 'p14apoyos',
 'scian',
 'emp_ppal',
 'tue_ppal',
 'trans_ppal',
 'mh_fil2',
 'mh_col',
 'sec_ins']

In [27]:
df_copy.shape

(313968, 74)

In [28]:
len(numericos) + len (categoricos) + 3

74

In [29]:
df_transform = pd.DataFrame()
dicc_transform = {}

In [30]:
for element in categoricos:
    i = 0
    column = element
    
    print(element)

    grouped = pd.DataFrame(df_copy[column].dropna().value_counts())
    grouped.head()

    grouped.reset_index(inplace=True)
    grouped.columns

    grouped.rename(columns={0: 'Key'}, inplace=True)
    grouped.columns

    grouped

    list_ = []
    for row in grouped[column]:
    #    print("%.2f" % (row/df_copy.shape[0]))
        list_.append(row/df_copy.shape[0])

    list_

    grouped[column] = list_
    grouped

    dict_ = grouped.to_dict(orient='split')
    dict_.keys()

    dict_.pop('index')
    dict_.pop('columns')
    dict_

    dict__ = {}

    for line in dict_['data']:
        #print(line[1], ' : ', line[0])
        dict__[line[0]] = line[1]
        i = i + 1
    dict__
    print(i)
        
    df_transform[column] = df_copy[column].replace(dict__)
    print(df_copy[column].unique())
    print(df_transform[column].unique())


est
4
[10 30 20 40]
[0.12986037 0.26940644 0.4877376  0.11299559]
t_loc
4
[1 2 3 4]
[0.59414017 0.13116623 0.12226405 0.15242955]
sex
2
[2 1]
[0.52284628 0.47715372]
l_nac_c
41
[  9.  20.  15.  13.  30.  21.  16.  17.   7.  31.  29.  12.  14.  28.
 200.  32.  11.   5.  10.  22.   2.  24.   1.  25. 415.   8.   3. 221.
   4.   6. 300.  19.  18. 400.  33.  27.  23.  26. 225. 100. 500.]
[5.23683942e-02 4.03066555e-02 4.24501860e-02 2.42317688e-02
 4.81259237e-02 4.17717729e-02 3.66279366e-02 2.09384396e-02
 4.05136829e-02 3.32486113e-02 2.61778270e-02 3.87873923e-02
 4.50014014e-02 2.40916272e-02 1.12431840e-03 3.37422922e-02
 4.47274882e-02 2.99998726e-02 3.06368802e-02 2.15499669e-02
 1.71450594e-02 3.40830913e-02 2.63689293e-02 3.47169138e-02
 1.33771595e-04 2.73085155e-02 1.26477858e-02 3.24555369e-03
 2.42954696e-02 1.96516842e-02 1.87917240e-04 2.98087703e-02
 2.60631657e-02 2.73913265e-04 1.91102278e-05 3.12356673e-02
 9.40860215e-03 2.66906182e-02 1.27401519e-05 6.37007593e-06]
cs_

In [35]:
df_transform['ent'] = df_copy.ent

In [36]:
df_transform['mun'] = df_copy.mun

In [37]:
df_transform['loc'] = df_copy['loc']

In [38]:
df_transform[numericos] = df_copy[numericos]

In [39]:
df_transform.columns

Index(['est', 't_loc', 'sex', 'l_nac_c', 'cs_p12', 'cs_p13_1', 'cs_p13_2',
       'cs_p17', 'e_con', 'clase1', 'clase2', 'clase3', 'pos_ocu', 'seg_soc',
       'rama', 'c_ocu11c', 'ing7c', 'dur9c', 'emple7c', 'medica5c', 'buscar5c',
       'rama_est1', 'rama_est2', 'dur_est', 'ambito1', 'ambito2', 'tue1',
       'tue2', 'tue3', 'busqueda', 'd_ant_lab', 'd_cexp_est', 'dur_des',
       'sub_o', 's_clasifi', 'remune2c', 'pre_asa', 'tip_con', 'dispo',
       'nodispo', 'c_inac5c', 'pnea_est', 'niv_ins', 'eda5c', 'eda7c',
       'eda12c', 'eda19c', 'hij5c', 'domestico', 'tpg_p8a', 'tcco', 'cp_anoc',
       'imssissste', 'ma48me1sm', 'p14apoyos', 'scian', 'emp_ppal', 'tue_ppal',
       'trans_ppal', 'mh_fil2', 'mh_col', 'sec_ins', 'eda', 'nac_dia',
       'nac_mes', 'nac_anio', 'anios_esc', 'hrsocup', 'ingocup', 'ing_x_hrs',
       't_tra', 'ent', 'mun', 'loc'],
      dtype='object')

In [40]:
df_transform.shape

(313968, 74)

In [41]:
file = "../../dataframes/enoe/enoe_transf_2016.csv"

In [42]:
df_transform.to_csv(path_or_buf=file)