In [1]:
import pandas as pd
import numpy as np

## Vivienda

In [9]:
file = "../../dataframes/enh/enh_clean_2016.csv"

In [10]:
df = pd.read_csv(filepath_or_buffer=file)

In [11]:
df.shape

(50643, 63)

In [12]:
df.isnull().any().any()

False

In [13]:
df.head()

Unnamed: 0  tipo_viv  mat_pared  mat_techos  mat_pisos  ais_techos  \
0           0         1          8           9          3           2   
1           1         1          8           9          3           2   
2           2         1          8           9          3           2   
3           3         1          8           9          3           2   
4           4         1          8           9          2           2   

   ais_pared  ais_ventan  ais_otro  cocina_dor ...   internet  tv_paga  \
0          2           2         2           2 ...          1        1   
1          2           2         2           2 ...          1        1   
2          2           2         9           2 ...          1        1   
3          2           2         2           2 ...          1        1   
4          2           2         2           2 ...          2        1   

   auto_pick  tot_resid  tot_hog  tam_loc  est_socio  ent  mun  loc  
0          1          4        1        1          3    1    1    1  
1          2          2        1        1          3    1    1    1  
2          1          2        1        1          3    1    1    1  
3          1          4        1        1          3    1    1    1  
4          1          4        1        1          3    1    1    1  

[5 rows x 63 columns]

In [14]:
df_copy = df.copy()

In [15]:
df_copy.drop(labels=['Unnamed: 0'], axis=1, inplace=True)

In [16]:
df_copy.columns

Index(['tipo_viv', 'mat_pared', 'mat_techos', 'mat_pisos', 'ais_techos',
       'ais_pared', 'ais_ventan', 'ais_otro', 'cocina_dor', 'cuart_dorm',
       'num_cuarto', 'disp_agua', 'dotac_agua', 'uso_compar', 'sanit_agua',
       'bano_comp', 'bano_excus', 'bano_regad', 'drenaje', 'disp_elect',
       'focos_inca', 'focos_ahor', 'combustible', 'eli_basura', 'lavadero',
       'fregadero', 'regadera', 'rega_elect', 'tinaco_azo', 'cisterna',
       'pileta', 'calent_sol', 'calent_gas', 'medidor_luz', 'bomba_agua',
       'tanque_gas', 'aire_acond', 'calefacc', 'chimenea', 'repar_pard',
       'repar_tech', 'repar_agua', 'repar_dren', 'repar_cabl', 'const_dorm',
       'const_coci', 'const_bano', 'const_neg', 'tenencia', 'computador',
       'tel_fijo', 'celular', 'internet', 'tv_paga', 'auto_pick', 'tot_resid',
       'tot_hog', 'tam_loc', 'est_socio', 'ent', 'mun', 'loc'],
      dtype='object')

In [17]:
numericos = ['cuart_dorm', 'num_cuarto', 'bano_comp', 'bano_excus', 'bano_regad', 'focos_inca', 
             'focos_ahor', 'tot_resid', 'tot_hog' ,'tam_loc', 'est_socio']

In [18]:
categoricos = ['tipo_viv', 'mat_pared', 'mat_techos', 'mat_pisos', 'ais_techos','ais_pared', 
               'ais_ventan', 'ais_otro', 'cocina_dor', 'disp_agua', 'dotac_agua', 'uso_compar', 
               'sanit_agua', 'drenaje', 'disp_elect', 'combustible', 'eli_basura', 'lavadero',
               'fregadero', 'regadera', 'rega_elect', 'tinaco_azo', 'cisterna',
       'pileta', 'calent_sol', 'calent_gas', 'medidor_luz', 'bomba_agua',
       'tanque_gas', 'aire_acond', 'calefacc', 'chimenea', 'repar_pard',
       'repar_tech', 'repar_agua', 'repar_dren', 'repar_cabl', 'const_dorm',
       'const_coci', 'const_bano', 'const_neg', 'tenencia', 'computador',
       'tel_fijo', 'celular', 'internet', 'tv_paga', 'auto_pick',
              ]

In [19]:
df_copy.shape

(50643, 62)

In [21]:
len(numericos) + len (categoricos) + 3

62

In [24]:
df_transform = pd.DataFrame()
dicc_transform = {}

In [43]:
for element in categoricos:
    i = 0
    column = element
    
    print(element)

    grouped = pd.DataFrame(df_copy[column].dropna().value_counts())
    grouped.head()

    grouped.reset_index(inplace=True)
    grouped.columns

    grouped.rename(columns={0: 'Key'}, inplace=True)
    grouped.columns

    grouped

    list_ = []
    for row in grouped[column]:
    #    print("%.2f" % (row/df_copy.shape[0]))
        list_.append(row/df_copy.shape[0])

    list_

    grouped[column] = list_
    grouped

    dict_ = grouped.to_dict(orient='split')
    dict_.keys()

    dict_.pop('index')
    dict_.pop('columns')
    dict_

    dict__ = {}

    for line in dict_['data']:
        #print(line[1], ' : ', line[0])
        dict__[line[0]] = line[1]
        i = i + 1
    dict__
    print(i)
        
    df_transform[column] = df_copy[column].replace(dict__)
    print(df_copy[column].unique())
    print(df_transform[column].unique())


tipo_viv
5
[1 2 3 4 5]
[9.54998717e-01 3.71423494e-02 7.44426673e-03 3.35683115e-04
 7.89842624e-05]
mat_pared
8
[8 7 1 3 6 2 4 5]
[9.04290820e-01 6.05414371e-02 1.06628754e-03 3.45556148e-03
 2.54329325e-02 5.52889837e-04 1.91536836e-03 2.74470312e-03]
mat_techos
9
[9 7 3 6 1 8 4 5 2]
[7.90000592e-01 1.00704935e-02 1.09511680e-01 2.40507079e-02
 4.14667378e-04 1.20253539e-02 4.52579823e-02 3.13962443e-03
 5.52889837e-03]
mat_pisos
3
[3 2 1]
[0.52510712 0.46158403 0.01330885]
ais_techos
3
[2 9 1]
[0.94218352 0.00803665 0.04977983]
ais_pared
3
[2 9 1]
[0.98116225 0.00708884 0.01174891]
ais_ventan
3
[2 9 1]
[0.9864542 0.0057856 0.0077602]
ais_otro
3
[2 9 1]
[0.992457   0.00564737 0.00189562]
cocina_dor
2
[2 1]
[0.93276465 0.06723535]
disp_agua
2
[1 2]
[0.80747586 0.19252414]
dotac_agua
5
[1 2 4 3 5]
[0.74612483 0.14691073 0.0343779  0.04602808 0.02655846]
uso_compar
2
[2 1]
[0.96042888 0.03957112]
sanit_agua
3
[1 2 3]
[0.76290899 0.20087673 0.03621428]
drenaje
5
[1 2 5 4 3]
[0.77908102 0

In [50]:
df_transform['ent'] = df_copy.ent

In [51]:
df_transform['mun'] = df_copy.mun

In [52]:
df_transform['loc'] = df_copy['loc']

In [53]:
df_transform[numericos] = df_copy[numericos]

In [54]:
df_transform.columns

Index(['tipo_viv', 'mat_pared', 'mat_techos', 'mat_pisos', 'ais_techos',
       'ais_pared', 'ais_ventan', 'ais_otro', 'cocina_dor', 'disp_agua',
       'dotac_agua', 'uso_compar', 'sanit_agua', 'drenaje', 'disp_elect',
       'combustible', 'eli_basura', 'lavadero', 'fregadero', 'regadera',
       'rega_elect', 'tinaco_azo', 'cisterna', 'pileta', 'calent_sol',
       'calent_gas', 'medidor_luz', 'bomba_agua', 'tanque_gas', 'aire_acond',
       'calefacc', 'chimenea', 'repar_pard', 'repar_tech', 'repar_agua',
       'repar_dren', 'repar_cabl', 'const_dorm', 'const_coci', 'const_bano',
       'const_neg', 'tenencia', 'computador', 'tel_fijo', 'celular',
       'internet', 'tv_paga', 'auto_pick', 'ent', 'mun', 'loc', 'cuart_dorm',
       'num_cuarto', 'bano_comp', 'bano_excus', 'bano_regad', 'focos_inca',
       'focos_ahor', 'tot_resid', 'tot_hog', 'tam_loc', 'est_socio'],
      dtype='object')

In [55]:
df_transform.shape

(50643, 62)

In [48]:
file = "../../dataframes/enh/enh_transf_2016.csv"

In [49]:
df_transform.to_csv(path_or_buf=file)